### ISSUE TITLE
Delete and publish post checkbox

### ISSUE THREAD

**Issue by the94air** [jeanquark/ajax-crud#1]
I notice that both of them doesn't return error or success message, also post don't disappear on delete

**Comment by jeanquark** [comment]
Hello Abdalla,

Thank you very much for your message. I tried to reimplement the issue you
had with the post delete and the published box but everything was working
fine for me. I've also just finished testing the app with the latest
versions of Google Chrome, Firefox, Safari, Opera and IE without any issue.

Are you experimenting the same problem when browsing the demo (
http://www.jmkleger.com/demo/ajax_crud)?

Which browser version are you using?

2017-02-21 10:04 GMT+01:00 Abdalla Mahmoud <notifications@github.com>:

**Comment by the94air** [comment]
I have tried it in windows 7
Version 51.0.2704.79 -> 6 hours before now
Version 56.0.2924.87 -> now 
And also the same problem in both of them

It would be a good idea if you add a fixed Font-awesome spinner. so the user know that request is possessing
